name: AtomPvPbot
version: 1.0.0
main: com.ejyqyl.atompvpbot.AtomPvPbot
api-version: '1.21'
author: ejyqyl
website: https://github.com/aqkooo
description: Enterprise PvP Bot & Combat Training Plugin for Paper 1.21+

softdepend:
  - PlaceholderAPI

commands:
  pvpbot:
    description: Master command for AtomPvPbot
    aliases: [botfight, pvpbotai, atombot]
    permission: atompvpbot.use
    permission-message: "<gradient:#BC00FD:#7670E5>У вас нет прав на использование этой команды.</gradient>"

permissions:
  atompvpbot.use:
    description: Allows opening main menu
    default: true
  atompvpbot.fight:
    description: Allows starting a PvP bot fight
    default: true
  atompvpbot.create:
    description: Allows spawning a bot in the world
    default: true
  atompvpbot.remove:
    description: Allows removing a spawned bot
    default: true
  atompvpbot.stats:
    description: Allows viewing player stats
    default: true
  atompvpbot.difficulty:
    description: Allows selecting bot difficulty
    default: true
  atompvpbot.arena:
    description: Allows managing arenas
    default: op
  atompvpbot.kit:
    description: Allows managing kits
    default: op
  atompvpbot.admin:
    description: Full administrative control over AtomPvPbot
    default: op
